name: SA-call

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-reusable:
    uses: praveenadmin/BH-Reusable-Templates/.github/workflows/reusable-deploy.yaml@main
    with:
      templateFile: ./BH-Reusable-Templates/templates/main.bicep
      parametersFile: ./BH-Reusable-Templates/parameters/storage.json  
      resourceGroup: 
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      PAT: ${{ secrets.PAT }} 